</div>
    <div id="footer">
        <div class="ui three column stackable grid">
            <div class="column">
                <div class="ui horizontal icon divider">
                    <i class="circular list icon"></i>
                </div>
                <div class="ui list">
                    <a href="#" class="item">
                        <i class="home icon"></i>
                        Home
                    </a>
                    <a href="#" class="item">
                        <i class="user icon"></i>
                        About
                    </a>
                    <a href="#" class="item">
                        <i class="archive icon"></i>
                        Demo
                    </a> 
                    <a href="#" class="item">
                        <i class="mail icon"></i>
                        Contact
                    </a>
                </div>
            </div>
            
            <div class="column">
                <div class="ui horizontal icon divider">
                    <i class="circular chat icon"></i>
                </div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eros turpis, sodales id neque quis, gravida posuere elit. Integer eget ex vitae arcu pretium bibendum id ut enim. Vestibulum dictum magna non lacus congue fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam molestie blandit nunc egestas efficitur. Sed pharetra, mauris non faucibus egestas, tortor nulla posuere risus, nec hendrerit turpis orci a arcu. Morbi ante urna, vulputate vel commodo ut, ornare ac quam. Integer at tellus lacus. Nunc non laoreet purus. Aenean ultrices neque eget diam maximus, ac egestas sapien tincidunt. Nam ornare dolor at quam imperdiet, sed dignissim orci rhoncus. Curabitur feugiat hendrerit turpis, eu scelerisque dolor sodales nec.</p>
            </div>
            
            <div class="column">
                <div class="ui horizontal icon divider">
                    <i class="circular pencil icon"></i>
                </div>
                <div class="ui small feed">
                    <div class="event">
                        <div class="label">
                            <img src="images/statue.jpg" alt="Statue of Liberty" />
                        </div>
                        <div class="content">
                            <div class="summary">
                                <a href="#">Hello World</a> Blog post
                                <div class="date">Just Now</div>
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="label">
                            <img src="images/statue.jpg" alt="Statue of Liberty" />
                        </div>
                        <div class="content">
                            <div class="summary">
                                <a href="#">New Theme</a> Blog post
                                <div class="date">1st February, 2015</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
</html>