<?php echo $this->doctype(); ?>

<html lang="en">
    
<head>

    
    <!-- CSS -->
    <?php
    $basePath = $this->basePath();
    $this->headLink()->appendStylesheet($basePath . '/css/app.css', 'all')
                     ->prependStylesheet('http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.8.1/semantic.min.css', 'all');
    echo $this->headLink();
    ?>

    
    <!-- JavaScripts -->
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.11/angular.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.8.1/semantic.min.js"></script>        
    <script type="text/javascript" src="js/scripts.js"></script>        

    
    <!-- Section CSS and JavaScript -->
    <!-- Demo 
    <link rel="stylesheet" type="text/css" href="demo.css">
    -->
    <!-- Used with Tab History !-->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.address/1.6/jquery.address.min.js"></script>
    
    
    <!-- Meta tags -->
    <title>Theme Name</title>
    <meta charset="utf-8" >
    <meta name="Description" CONTENT="" >
    <meta name="google-site-verification" content="" >
    <meta name="robots" content="" >
</head>
<body ng-app="">

