
<div id="m_menu" class="ui floating sidebar vertical menu inverted active ">
    <a href="index.php#" class="item">
        <i class="home icon"></i>
        Home
    </a>
    <a href="#" class="item">
        <i class="user icon"></i>
        About
    </a>
    <a href="#" class="item">
        <i class="archive icon"></i>
        Demo
    </a>
    <a href="#" class="item">
        <i class="archive icon"></i>
        Contact
    </a>
</div>
<div id="header">
    <div id="mainHead">
        <div id="menu" class="ui pointing menu inverted fluid four item">
          <a class="item">
            <i class="home icon"></i> Home
          </a>

          <a class="item">
            <i class="user icon"></i> About
          </a>
            
          <a class="item">
            <i class="archive icon"></i> Demo
          </a>

          <a class="item">
            <i class="mail icon"></i> Contact
          </a> 
        </div>

        <div id="m_btn" class="ui labeled icon black button">
          <i class="icon list layout"></i>
          Menu
        </div>
        <div class="ui icon huge header inverted">
            <i class="circular inverted chat icon"></i>Veni. Vidi. Vici.
        </div>
        <h2 class="ui header inverted">
            <i class="chat icon"></i>
            Veni. Vidi. Vici.
        </h2>
    </div>
    <img id="mainImage" src="../images/header.jpg" alt="New York" />
</div>
<div id="content">