<?php echo $this->doctype(); ?>

<html lang="en">
    
<head>

    <!-- CSS -->
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.7.3/semantic.min.css" />
    <link rel="stylesheet" href="css/main.css" />
    <!--<link rel="stylesheet" href="css/semantic_cdn_overrides.css" />
    -->
    
    <!-- JavaScripts -->
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.10/angular.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.7.3/semantic.min.js"></script>        

    
    <!-- Section CSS and JavaScript -->
    <!-- Demo 
    <link rel="stylesheet" type="text/css" href="demo.css">
    -->
    <!-- Used with Tab History !-->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.address/1.6/jquery.address.min.js"></script>
    
    
    <!-- Meta tags -->
    <title>Theme Name</title>
    <meta charset="utf-8" >
    <meta name="Description" CONTENT="" >
    <meta name="google-site-verification" content="" >
    <meta name="robots" content="" >
</head>
<body ng-app="">

