<div id="homethree" class="ui three column grid stackable divided">
    <div class="column">
        <h3><i class="icon circular inverted blue pencil"></i></h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tria genera bonorum; Quid, si etiam iucunda memoria est praeteritorum malorum? Si verbum sequimur, primum longius verbum praepositum quam bonum. De vacuitate doloris eadem sententia erit. Quid, quod res alia tota est?
        </p>
        <div class="ui fade reveal">
            <img src="images/mainimage.jpg" alt="New York by Night" class="ui circular image visible content" />
            <img src="images/reveal.png" alt="New York" class="ui circular image hidden content pop" data-content="New York by night" data-title="New York" data-position="top center" data-variation="inverted" />
        </div>
    </div>
    <div class="column">
        <h3><i class="icon circular inverted blue pencil"></i></h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tria genera bonorum; Quid, si etiam iucunda memoria est praeteritorum malorum? Si verbum sequimur, primum longius verbum praepositum quam bonum. De vacuitate doloris eadem sententia erit. Quid, quod res alia tota est?
        </p>
        <div class="ui fade reveal">
            <img src="images/mainimage.jpg" alt="New York by Night" class="ui circular image visible content" />
            <img src="images/reveal.png" alt="New York" class="ui circular image hidden content pop" data-content="New York by night" data-title="New York" data-position="top center" data-variation="inverted" />
        </div>
    </div>
    <div class="column">
        <h3><i class="icon circular inverted blue pencil"></i></h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tria genera bonorum; Quid, si etiam iucunda memoria est praeteritorum malorum? Si verbum sequimur, primum longius verbum praepositum quam bonum. De vacuitate doloris eadem sententia erit. Quid, quod res alia tota est?
        </p>
        <div class="ui fade reveal">
            <img src="images/mainimage.jpg" alt="New York by Night" class="ui circular image visible content" />
            <img src="images/reveal.png" alt="New York" class="ui circular image hidden content pop" data-content="New York by night" data-title="New York" data-position="top center" data-variation="inverted" />
        </div>
    </div>
    
    <div id="center">
        <div class="ui button icon labeled basic">
            <i class="icon shuffle"></i> 
            Animate
        </div>
    </div>
        
    
</div>